version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: false

linters:
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - funlen
    - gocyclo
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
    - gocognit
    - nolintlint
    - godot
    - promlinter
    - whitespace
    - dupword
    - predeclared
  disable:
    - errcheck
    - gosec
    - staticcheck

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocognit:
      min-complexity: 30
    funlen:
      lines: 110
      statements: 60
    gocyclo:
      min-complexity: 20
    gocritic:
      enabled-tags:
        - performance
        - diagnostic
        - style
      disabled-checks:
        - hugeParam
        - importShadow
        - ifElseChain
        - commentedOutCode
    nolintlint:
      require-explanation: true
      require-specific: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0