# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: test

on:
  push:
    branches: ["main"]
  workflow_call: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-build-env
      - name: Unit Test
        run: go test -race -v ./...
      - name: Run benchmarks
        run: go test -benchmem -bench . -run ^$ ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-build-env
      - name: Lint library
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
